name: Docker Build -> Push -> Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Build JAR
      - name: Build Jar
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-ci-demo:latest .

      # 6. Push Docker Image
      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-ci-demo:latest

      # 7. Deploy to EC2 via SSH
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker ps -q --filter "publish=8080" | xargs -r docker stop
            docker ps -aq --filter "publish=8080" | xargs -r docker rm
            docker stop spring-demo || true
            docker rm spring-demo || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-ci-demo:latest
            docker run -d --name spring-demo -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-ci-demo:latest